
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-depl
spec:
  replicas: 1    
  selector:
   matchLabels:
     app: reverseproxy
  template:
     metadata:
       labels:
         app: reverseproxy
     spec:
       containers:
         - name: reverseproxy-con
           image: 1ryber/reverseproxy
           resources:
             requests:
               cpu: 100m
               memory: 100Mi
             limits:
               cpu: 200m
               memory: 200Mi 
           ports:
            - containerPort: 8080
           
---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy
  type: LoadBalancer    
